---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Ensure fail2ban is started and enabled
  service:
    name: fail2ban
    state: started
    enabled: true

- name: Install logrotate
  apt:
    name: logrotate
    state: present

- name: Configure logrotate for nginx
  copy:
    dest: /etc/logrotate.d/nginx
    content: |
      /var/log/nginx/*.log {
          daily
          missingok
          rotate 14
          compress
          delaycompress
          notifempty
          create 0640 www-data adm
          sharedscripts
          postrotate
              [ -f /var/run/nginx.pid ] && kill -USR1 `cat /var/run/nginx.pid`
          endscript
      }
    owner: root
    group: root
    mode: "0644"
